export const pricings = [
   {
    name:'dentistryOwner',
    accessPages: [
      'Videos',
      ' Podcasts and Webinars',
      ' Assist',
      ' Blogs',
      'Student',
      ' Business and Finance',
      ' Downloads',
      'Wellbeing',
      'Courses',
      'Guidelines',
      'Workflows',
      'Forum',
      'Ability to add and assign employees to track development on videos',
    ],
    productId: 'DO_50_m',
    price: 50,
    privilege: 3,
  },
    {
    name:'dentistryOwnerYearly',
    accessPages: [
      'Videos',
      ' Podcasts and Webinars',
      ' Assist',
      ' Blogs',
      'Student',
      ' Business and Finance',
      ' Downloads',
      'Wellbeing',
      'Courses',
      'Guidelines',
      'Workflows',
      'Forum',
      'Ability to add and assign employees to track development on videos',
    ],
    productId: 'DO_525_y',
    price: 525,
    privilege: 3,
  },
   {
    name:'premium',
    accessPages: [
      'Videos',
      ' Podcasts and Webinars',
      ' Assist',
      ' Blogs',
      'Student',
      ' Business and Finance',
      ' Downloads',
      'Wellbeing',
      'Courses',
      'Guidelines',
      'Workflows',
      'Forum',
    ],
    productId: 'pm_15_m',
    price: 15.99,
    privilege: 2,
  },
   {
    name:'premiumYearly',
    accessPages: [
      'Videos',
      ' Podcasts and Webinars',
      ' Assist',
      ' Blogs',
      'Student',
      ' Business and Finance',
      ' Downloads',
      'Wellbeing',
      'Courses',
      'Guidelines',
      'Workflows',
      'Forum',
    ],
    productId: 'pm_165_y',
    price: 165,
    privilege: 2,
  },
   {
    name:'starter',
    accessPages: [
      'Videos (2 free videos)',
      'Podcasts only',
      'Blogs',
      'Forum (View only)',
    ],
    productId: '',
    price: 0,
    privilege: 0,
  },
   {
    name:'starterYearly',
    accessPages: [
      'Videos (2 free videos)',
      'Podcasts only',
      'Blogs',
      'Forum (View only)',
    ],
    productId: '',
    price: 0,
    privilege: 0,
  },
   {
    name:'student',
    accessPages: [
      'Videos',
      ' Podcasts and Webinars',
      ' Blogs',
      ' Student',
      ' Workflows',
      ' Forum',
    ],
    productId: 'sm_7_m',
    price: 6.99,
    privilege: 1,
  },
   {
    name:'studentYearly',
    accessPages: [
      'Videos',
      ' Podcasts and Webinars',
      ' Blogs',
      ' Student',
      ' Workflows',
      ' Forum',
    ],
    productId: 'sy_65_y',
    price: 65,
    privilege: 1,
  },
];
